&Procurar
196
Procurar registro
&Filtrar
124
Filtragem e ordenação de registros
&Gravar
199
Gravar registro
&Cancelar
30
Cancelar inclusão/modificação no registro
&Excluir
24
Excluir registro
P&rimeiro
192
Posicionar no primeiro registro
&Anterior
193
Posicionar no registro anterior
Próxi&mo
194
Posicionar no próximo registro
&Ultimo
195
Posicionar no último registro
A&juda
21
Ajuda do sistema
&Fechar
52
Fechar janela
