{
 Arquivos de Classe de tabelas
}

  DAtividades in 'DAtividades.Pas',
  DClientes in 'DClientes.Pas',
  DConsulta_Itens_Venda in 'DConsulta_Itens_Venda.Pas',
  DFornecedores in 'DFornecedores.Pas',
  DFornecedores_2 in 'DFornecedores_2.Pas',
  DItens_Venda in 'DItens_Venda.Pas',
  DProdutos in 'DProdutos.Pas',
  DUSER_AGENDA in 'DUSER_AGENDA.Pas',
  DUSER_BARRA_F in 'DUSER_BARRA_F.Pas',
  DUSER_GRUPOS in 'DUSER_GRUPOS.Pas',
  DUSER_LOG in 'DUSER_LOG.Pas',
  DUSER_MENU_LATERAL in 'DUSER_MENU_LATERAL.Pas',
  DUSER_MENU_SUPERIOR in 'DUSER_MENU_SUPERIOR.Pas',
  DUSER_NOMES in 'DUSER_NOMES.Pas',
  DUSER_TABELAS in 'DUSER_TABELAS.Pas',
  DVendas in 'DVendas.Pas',

